### ISSUE TITLE
Error in console "Could not pass event PlayerInteractEvent to ProtectedDebugStick v2.3.0"

### ISSUE THREAD

**Issue by KoczkodanChaosu** [MachiganMC/ProtectedDebugStick#20]
Hello, this error appears in my console when I try to edit nether_portal block. I blacklisted nether_portal in config and the error stopped showing in console, so I just wanted to report that this issue exist, but it's not a big deal.

[Server thread/ERROR]: Could not pass event PlayerInteractEvent to ProtectedDebugStick v2.3.0
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:536) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:503) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1640) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1152) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1131) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1124) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1108) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1019) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Cannot set property BlockStateEnum{name=axis, clazz=class net.minecraft.core.EnumDirection$EnumAxis, values=[x, z]} to y on Block{minecraft:nether_portal}, it is not an allowed value
at net.minecraft.world.level.block.state.IBlockDataHolder.a(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at org.bukkit.craftbukkit.v1_20_R1.block.data.CraftBlockData.set(CraftBlockData.java:113) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at org.bukkit.craftbukkit.v1_20_R1.block.impl.CraftPortal.setAxis(CraftPortal.java:27) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3808-Spigot-c62f4bd-44a4b56]
at be.machigan.protecteddebugstick.action.OrientableAction.modify(OrientableAction.java:17) ~[?:?]
at be.machigan.protecteddebugstick.event.PropertyEditEvent.editBlockData(PropertyEditEvent.java:77) ~[?:?]
at be.machigan.protecteddebugstick.event.PropertyEditEvent.editBlock(PropertyEditEvent.java:46) ~[?:?]
at be.machigan.protecteddebugstick.event.OnUse.handleRightClick(OnUse.java:70) ~[?:?]
at be.machigan.protecteddebugstick.event.OnUse.onUse(OnUse.java:45) ~[?:?]
at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
... 22 more

**Comment by MachiganMC** [comment]
Hello, thank you for the report !
I fixed it in 0aeb7706bf0ebd7176273f8162b190a4ec3625e9.
It will be applied in the next update.
